### ISSUE TITLE
Raiblocks store generator

### ISSUE THREAD

**Issue by bluepnume** [brainblocks/brainstorm#2]
It would be awesome to have a site where merchants can set up their own store, upload product images, descriptions, prices etc. then have it automatically use brainblocks to process payments.

So, for example, a merchant could create `lavalamps.brainblockstore.com` to sell lava lamps, without any coding needed.

**Comment by lucasrim** [comment]
Preferences on stack? I can work on this, know Node and Rails, front-end have a preference for React.

**Comment by bluepnume** [comment]
Hey! Thanks for volunteering to take this one up. Honestly, if you're building it out, it's totally your prerogative to pick up whichever language/framework you like. I do love React though, so sounds great to me. So far I've been doing all of the back-end work in Node, but entirely up to you what suits you best.

Let me know if you'd like any repos set up in https://github.com/brainblocks

**Comment by bluepnume** [comment]
@lucasrim -- any luck with this one?

**Comment by schenkty** [comment]
Hey is there any update on this one? Would love for it be implemented

**Comment by itsaphel** [comment]
Honestly, a fair bit of reinventing the wheel here.

What's wrong with using existing store solutions and just implementing gateway support?

**Comment by bluepnume** [comment]
I'm totally open to that @itsaphel -- the main thing for me is to have some kind of platform, whether or not it using existing store solutions, that someone can set up without having to set up their own domain or website. That doesn't necessarily have to involve building everything from scratch.

**Comment by schenkty** [comment]
Going to close since this happened with https://nexus.brainblocks.io
